// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzyOgETrvHQ7lrq-WPS_elBC2TyOR3Rxs',
    appId: '1:328440071001:web:a22c242a3637815f820248',
    messagingSenderId: '328440071001',
    projectId: 'amberiitism',
    authDomain: 'amberiitism.firebaseapp.com',
    storageBucket: 'amberiitism.appspot.com',
    measurementId: 'G-2E9SJRH59M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSs8JlLYSAGtqiUG0ObRPBCm5Xbu2tknQ',
    appId: '1:328440071001:android:ef9f0aab6863a31d820248',
    messagingSenderId: '328440071001',
    projectId: 'amberiitism',
    storageBucket: 'amberiitism.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvzJsZqScJv7hcoQCMBqrH_OKp1QloyPc',
    appId: '1:328440071001:ios:a705791ce5753b3a820248',
    messagingSenderId: '328440071001',
    projectId: 'amberiitism',
    storageBucket: 'amberiitism.appspot.com',
    iosClientId: '328440071001-tqa96c3gq4o33i183l530cvh2vb9m2cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.amberWebsite',
  );
}
